In [ ]:
# =========================
# 1. Load and merge data
# =========================
# Import and Read the GALAH Data
from astropy.io import fits
import pandas as pd

galah = fits.open("GALAH_DR3_main_allstar_v2.fits")

galah.info()

Filename: GALAH_DR3_main_allstar_v2.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()
  1                1 BinTableHDU    904   588571R x 197C   [16A, K, K, K, 12A, K, K, 6A, 4A, K, E, D, E, E, 3A, E, D, E, D, K, E, E, E, D, E, D, D, D, K, E, E, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, K, K, D, D, D, D, D, D, D, D, D, D, E, E, K, D, D, D, D, D, K, E, E, E, E, E, E, E, 3A, D, D, 4A, D, D, E, D]

In [ ]:
# Import and Read the Survey Catalogue
data = galah[1].data

df = pd.DataFrame(data)

df.head()

,star_id,sobject_id,dr2_source_id,dr3_source_id,survey_name,field_id,flag_repeat,wg4_field,wg4_pipeline,flag_sp,teff,e_teff,irfm_teff,irfm_ebv,irfm_ebv_ref,logg,e_logg,fe_h,e_fe_h,flag_fe_h,fe_h_atmo,vmic,vbroad,e_vbroad,chi2_sp,alpha_fe,e_alpha_fe,nr_alpha_fe,flag_alpha_fe,flux_A_Fe,chi_A_Fe,Li_fe,e_Li_fe,nr_Li_fe,flag_Li_fe,C_fe,e_C_fe,nr_C_fe,flag_C_fe,O_fe,e_O_fe,nr_O_fe,flag_O_fe,Na_fe,e_Na_fe,nr_Na_fe,flag_Na_fe,Mg_fe,e_Mg_fe,nr_Mg_fe,flag_Mg_fe,Al_fe,e_Al_fe,nr_Al_fe,flag_Al_fe,Si_fe,e_Si_fe,nr_Si_fe,flag_Si_fe,K_fe,e_K_fe,nr_K_fe,flag_K_fe,Ca_fe,e_Ca_fe,nr_Ca_fe,flag_Ca_fe,Sc_fe,e_Sc_fe,nr_Sc_fe,flag_Sc_fe,Sc2_fe,e_Sc2_fe,nr_Sc2_fe,flag_Sc2_fe,Ti_fe,e_Ti_fe,nr_Ti_fe,flag_Ti_fe,Ti2_fe,e_Ti2_fe,nr_Ti2_fe,flag_Ti2_fe,V_fe,e_V_fe,nr_V_fe,flag_V_fe,Cr_fe,e_Cr_fe,nr_Cr_fe,flag_Cr_fe,Cr2_fe,e_Cr2_fe,nr_Cr2_fe,flag_Cr2_fe,Mn_fe,e_Mn_fe,nr_Mn_fe,flag_Mn_fe,Co_fe,e_Co_fe,nr_Co_fe,flag_Co_fe,Ni_fe,e_Ni_fe,nr_Ni_fe,flag_Ni_fe,Cu_fe,e_Cu_fe,nr_Cu_fe,flag_Cu_fe,Zn_fe,e_Zn_fe,nr_Zn_fe,flag_Zn_fe,Rb_fe,e_Rb_fe,nr_Rb_fe,flag_Rb_fe,Sr_fe,e_Sr_fe,nr_Sr_fe,flag_Sr_fe,Y_fe,e_Y_fe,nr_Y_fe,flag_Y_fe,Zr_fe,e_Zr_fe,nr_Zr_fe,flag_Zr_fe,Mo_fe,e_Mo_fe,nr_Mo_fe,flag_Mo_fe,Ru_fe,e_Ru_fe,nr_Ru_fe,flag_Ru_fe,Ba_fe,e_Ba_fe,nr_Ba_fe,flag_Ba_fe,La_fe,e_La_fe,nr_La_fe,flag_La_fe,Ce_fe,e_Ce_fe,nr_Ce_fe,flag_Ce_fe,Nd_fe,e_Nd_fe,nr_Nd_fe,flag_Nd_fe,Sm_fe,e_Sm_fe,nr_Sm_fe,flag_Sm_fe,Eu_fe,e_Eu_fe,nr_Eu_fe,flag_Eu_fe,ra_dr2,dec_dr2,parallax_dr2,parallax_error_dr2,r_est_dr2,r_lo_dr2,r_hi_dr2,r_len_dr2,rv_galah,e_rv_galah,rv_gaia_dr2,e_rv_gaia_dr2,red_flag,ebv,snr_c1_iraf,snr_c2_iraf,snr_c3_iraf,snr_c4_iraf,flag_guess,v_jk,j_m,j_msigcom,h_m,h_msigcom,ks_m,ks_msigcom,ph_qual_tmass,w2mpro,w2mpro_error,ph_qual_wise,a_ks,e_a_ks,bc_ks,ruwe_dr2
0,03325271-6840304,131116000501002,4667368899326729856,4667368899326729856,galah_main,138,0,10k_2,lbol,0,4553.354492,137.060886,4138.0,0.048,sfd,4.714953,0.201216,-0.335019,0.120219,0,-0.109347,0.948537,9.345594,2.508091,0.587386,0.351368,0.079193,405.0,0,0.734470,0.807950,-0.183756,0.128548,1,1,NaN,NaN,-9223372036854775808,32,1.214647,0.213838,1,1,0.145268,0.114891,1,0,-0.088498,0.191551,1,0,0.467331,0.118618,1,0,NaN,NaN,1,32,0.440389,0.164718,1,0,0.402228,0.127618,1,0,0.427332,0.106208,1,0,NaN,NaN,0,0,0.690977,0.207313,18,0,NaN,NaN,-9223372036854775808,32,0.855374,0.307709,2,0,0.242551,0.152207,1,0,NaN,NaN,0,0,-0.113757,0.186462,1,0,0.645332,0.095744,6,0,NaN,NaN,-9223372036854775808,32,0.188081,0.134959,2,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,0.527863,0.153388,1,1,NaN,NaN,-9223372036854775808,32,NaN,NaN,16,32,NaN,NaN,2,32,NaN,NaN,2,32,0.163863,0.174535,1,0,NaN,NaN,4,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,2,32,NaN,NaN,1,32,53.221132,-68.674800,6.944819,0.014118,143.394475,143.102580,143.687543,509.572275,36.203999,0.183000,35.907078,1.795988,0,0.046502,6.313349,17.363254,31.274920,29.065174,0,13.705686,11.396,0.023,10.728,0.022,10.607,0.021,AAA,10.558,0.019,AAAU,0.082620,0.026685,2.198110,1.098764
1,03345385-6836362,131116000501003,4667362989451832448,4667362989451832448,galah_main,138,0,10k_0,lbol,256,3622.744629,104.983490,NaN,NaN,,4.691505,0.198562,NaN,NaN,17,0.340292,0.799639,14.891972,2.424655,2.149659,NaN,NaN,NaN,32,0.447427,0.131018,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,0,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,0,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,53.726021,-68.611051,10.360335,0.016036,96.252970,96.103515,96.402882,508.606085,55.373326,0.731789,NaN,NaN,0,0.000000,6.455616,18.462486,35.254047,32.247356,0,13.426032,11.060,0.024,10.425,0.023,10.255,0.025,AAA,10.121,0.021,AAAU,0.000000,0.000000,2.669922,1.184694
2,03422255-6841522,131116000501004,4667324643983679744,4667324643983679744,galah_main,138,0,10k_26,lbol,0,4852.475586,172.750969,4925.0,0.037,sfd,2.466885,0.223199,-1.170157,0.181902,0,-1.147935,1.202963,8.185776,2.876024,0.273358,0.273048,0.085366,7.0,0,0.522449,0.324545,1.070449,0.135366,1,1,NaN,NaN,1,32,0.759033,0.229369,1,1,-0.091090,0.129067,1,0,0.107714,0.221648,1,0,0.526840,0.127823,1,1,0.335639,0.124884,1,0,0.034968,0.181227,1,0,0.260766,0.137687,1,0,0.245278,0.116629,1,0,NaN,NaN,0,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,0.746994,0.337653,2,1,0.317531,0.167978,1,1,NaN,NaN,0,0,-0.430755,0.212472,1,0,0.750166,0.245068,8,1,-0.006910,0.204713,2,0,-0.400982,0.147994,2,1,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,1,32,NaN,NaN,2,32,NaN,NaN,-9223372036854775808,32,NaN,NaN,2,32,NaN,NaN,-9223372036854775808,32,-0.033738,0.192435,1,0,1.096292,0.145654,4,1,0.911001,0.193261,1,1,1.395719,0.123883,2,1,1.039035,0.166752,2,1,0.831204,0.144606,1,1,55.593979,-68.697931,0.266503,0.011894,3359.017111,3230.060002,3498.388825,506.137800,95.877998,0.151000,NaN,NaN,0,0.038746,6.735779,14.200917,24.748720,19.922360,0,13.730144,11.981,0.023,11.468,0.024,11.374,0.019,AAA,11.379,0.021,AABU,0.008262,0.029275,1.989632,0.991040
3,03373408-6841062,131116000501005,4667335913977929728,4667335913977929728,galah_main,138,0,10k_33,lbol,1,5588.500488,104.294555,5504.0,0.037,sfd,3.999357,0.186127,0.052395,0.099372,0,0.058992,1.111983,12.291694,2.374440,0.443703,-0.015430,0.053713,159.0,0,0.611203,0.873410,0.534573,0.111604,1,1,-0.012350,0.159103,1,1,-0.019165,0.177424,1,0,0.043523,0.084613,1,0,0.086088,0.130607,1,0,0.244746,0.097029,1,0,-0.066913,0.086889,1,0,-0.009887,0.128032,1,0,0.056808,0.104213,1,0,0.022938,0.082695,1,0,NaN,NaN,0,0,-0.143159,0.154505,18,0,0.10152,0.169092,2,0,NaN,NaN,-9223372036854775808,32,0.206086,0.117013,1,0,NaN,NaN,0,0,0.103309,0.131913,1,0,0.197035,0.199633,8,1,-0.194399,0.151458,2,0,0.044643,0.085905,3,0,-0.092225,0.159291,3,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,1,32,-0.017366,0.263792,2,0,NaN,NaN,16,32,NaN,NaN,2,32,NaN,NaN,2,32,-0.059826,0.134714,1,0,NaN,NaN,4,32,NaN,NaN,1,32,NaN,NaN,2,32,NaN,NaN,2,32,NaN,NaN,1,32,54.392072,-68.685002,1.214608,0.018661,804.187683,792.207994,816.528454,508.102011,7.130000,0.126000,NaN,NaN,0,0.000000,16.002312,26.176768,39.782626,27.754162,0,13.439095,12.135,0.024,11.760,0.022,11.710,0.023,AAA,11.730,0.021,AABU,0.000000,0.027920,1.577001,1.629809
4,03430488-6843208,131116000501006,4667323681911007232,4667323681911007232,galah_main,138,0,10k_41,lbol,1,5709.502930,109.203400,5725.0,0.040,sfd,4.181905,0.184704,-0.013732,0.111376,0,-0.012599,1.138507,12.961143,2.481610,0.366441,0.081023,0.080372,149.0,0,0.585344,1.021483,1.037844,0.118147,1,0,0.122847,0.167533,1,1,-0.030804,0.191105,1,0,-0.067560,0.095483,1,0,0.064595,0.151905,1,0,-0.080545,0.105142,1,0,-0.143940,0.096378,1,0,0.319648,0.141463,1,0,0.116323,0.112970,1,0,0.073589,0.091368,1,0,NaN,NaN,0,0,0.018990,0.173781,18,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,-9223372036854775808,32,0.041848,0.129925,1,0,NaN,NaN,0,0,0.012897,0.151319,1,0,0.387603,0.212163,8,1,0.005661,0.165390,2,0,-0.126564,0.116368,2,0,-0.181010,0.178974,3,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,1,32,0.118394,0.299674,2,0,NaN,NaN,-9223372036854775808,32,NaN,NaN,2,32,NaN,NaN,-9223372036854775808,32,0.022582,0.149301,1,0,NaN,NaN,4,32,NaN,NaN,1,32,NaN,NaN,2,32,NaN,NaN,2,32,NaN,NaN,1,32,55.770494,-68.722453,2.361054,0.019589,418.433568,415.005774,421.917429,505.910007,24.816000,0.163000,28.709490,1.654053,0,0.000000,14.395832,22.593675,36.087041,26.449470,0,12.554296,11.248,0.024,10.883,0.022,10.822,0.021,AAA,10.827,0.021,AAAU,0.000000,0.027920,1.508929,1.403180

In [5]:
# Import and Read the Gaia Data
gaia = fits.open("GALAH_DR3_VAC_GaiaEDR3_v2.fits")
gaia.info()

gaia_data = gaia[1].data
gaia_df = pd.DataFrame(gaia_data)
gaia_df.head()

Filename: GALAH_DR3_VAC_GaiaEDR3_v2.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()
  1  Joined        1 BinTableHDU    549   678423R x 114C   [16A, K, K, K, E, E, L, K, 29A, K, D, D, E, D, E, D, E, E, E, D, E, D, E, E, E, E, E, E, E, E, E, E, E, I, I, I, I, E, E, E, E, I, L, E, E, E, E, E, E, E, E, I, I, E, I, I, I, E, E, I, I, E, E, E, E, E, E, E, E, E, L, I, D, E, E, E, I, D, E, E, E, I, D, E, E, E, I, I, I, I, I, E, E, E, E, E, E, I, E, E, E, D, D, D, D, D, D, E, E, E, E, E, E, 5A]

,star_id,sobject_id,dr2_source_id,dr3_source_id,angular_distance,magnitude_difference,proper_motion_propagation,solution_id,designation,random_index,ref_epoch,ra,ra_error,dec,dec_error,parallax,parallax_error,parallax_over_error,pm,pmra,pmra_error,pmdec,pmdec_error,ra_dec_corr,ra_parallax_corr,ra_pmra_corr,ra_pmdec_corr,dec_parallax_corr,dec_pmra_corr,dec_pmdec_corr,parallax_pmra_corr,parallax_pmdec_corr,pmra_pmdec_corr,astrometric_n_obs_al,astrometric_n_obs_ac,astrometric_n_good_obs_al,astrometric_n_bad_obs_al,astrometric_gof_al,astrometric_chi2_al,astrometric_excess_noise,astrometric_excess_noise_sig,astrometric_params_solved,astrometric_primary_flag,nu_eff_used_in_astrometry,pseudocolour,pseudocolour_error,ra_pseudocolour_corr,dec_pseudocolour_corr,parallax_pseudocolour_corr,pmra_pseudocolour_corr,pmdec_pseudocolour_corr,astrometric_matched_transits,visibility_periods_used,astrometric_sigma5d_max,matched_transits,new_matched_transits,matched_transits_removed,ipd_gof_harmonic_amplitude,ipd_gof_harmonic_phase,ipd_frac_multi_peak,ipd_frac_odd_win,ruwe,scan_direction_strength_k1,scan_direction_strength_k2,scan_direction_strength_k3,scan_direction_strength_k4,scan_direction_mean_k1,scan_direction_mean_k2,scan_direction_mean_k3,scan_direction_mean_k4,duplicated_source,phot_g_n_obs,phot_g_mean_flux,phot_g_mean_flux_error,phot_g_mean_flux_over_error,phot_g_mean_mag,phot_bp_n_obs,phot_bp_mean_flux,phot_bp_mean_flux_error,phot_bp_mean_flux_over_error,phot_bp_mean_mag,phot_rp_n_obs,phot_rp_mean_flux,phot_rp_mean_flux_error,phot_rp_mean_flux_over_error,phot_rp_mean_mag,phot_bp_n_contaminated_transits,phot_bp_n_blended_transits,phot_rp_n_contaminated_transits,phot_rp_n_blended_transits,phot_proc_mode,phot_bp_rp_excess_factor,bp_rp,bp_g,g_rp,dr2_radial_velocity,dr2_radial_velocity_error,dr2_rv_nb_transits,dr2_rv_template_teff,dr2_rv_template_logg,dr2_rv_template_fe_h,l,b,ecl_lon,ecl_lat,zpt_ll2020,parallax_corr,r_med_geo,r_lo_geo,r_hi_geo,r_med_photogeo,r_lo_photogeo,r_hi_photogeo,flag_edr3dist
0,03325271-6840304,131116000501002,4667368899326729856,4667368899326729856,0.083785,-0.013575,True,1636042515805110273,Gaia EDR3 4667368899326729856,596651783,2016.0,53.221178,0.009769,-68.674790,0.009531,6.972027,0.010533,661.911926,141.719818,121.902536,0.013319,72.279162,0.013341,0.086752,0.142334,-0.140995,-0.113397,0.240424,-0.010643,-0.132408,0.229328,-0.191607,0.182561,345,0,345,0,2.222509,380.881836,0.012108,0.131463,31,True,1.383337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,26,0.020144,45,15,0,0.014056,35.719040,0,0,1.085421,0.171633,0.077456,0.143615,0.042170,-54.032757,-32.081009,1.047078,-42.140221,False,363,82306.762995,18.656384,4411.721191,13.398778,41,27925.465753,21.865519,1277.146240,14.223541,39,78734.341902,50.540962,1557.832275,12.507485,0,0,0,0,0,1.295882,1.716056,0.824763,0.891293,35.907078,1.795988,9,4000.0,3.0,0.0,284.403250,-42.173533,334.618455,-76.054642,-0.030388,7.002415,142.725815,142.426086,142.936722,142.844009,142.674469,143.048721,10033
1,03345385-6836362,131116000501003,4667362989451832448,4667362989451832448,0.057945,-0.018339,True,1636042515805110273,Gaia EDR3 4667362989451832448,781424142,2016.0,53.726071,0.009892,-68.611080,0.009834,10.389499,0.009953,1043.805298,247.463043,132.319208,0.014328,-209.116196,0.014810,0.070525,0.090014,-0.213000,-0.160717,-0.019907,-0.150510,0.123213,0.152045,-0.030694,0.076742,352,0,349,3,3.018957,398.713562,0.005762,0.026831,31,False,1.336658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,27,0.021137,45,14,0,0.012516,46.161114,0,0,1.116272,0.067901,0.115326,0.092623,0.013999,-31.598829,-51.641445,-0.334318,15.853956,False,341,82433.633822,28.601414,2882.152344,13.397106,41,22864.123568,23.285797,981.891357,14.440656,41,88592.419229,41.537354,2132.837402,12.379404,0,1,0,0,0,1.352076,2.061252,1.043550,1.017702,NaN,NaN,0,NaN,NaN,NaN,284.181366,-42.069696,334.998079,-76.226684,-0.032021,10.421520,95.959564,95.875595,96.049644,95.952316,95.884872,96.033737,10033
2,03422255-6841522,131116000501004,4667324643983679744,4667324643983679744,0.066286,-0.011477,True,1636042515805110273,Gaia EDR3 4667324643983679744,1245786055,2016.0,55.593978,0.009778,-68.697933,0.010073,0.260149,0.009733,26.728586,12.613773,-2.802182,0.012275,-12.298579,0.014316,0.012735,0.087802,-0.089912,-0.324936,0.042063,-0.280943,-0.101917,0.104369,-0.165599,-0.026526,361,0,361,0,-1.872344,310.165588,0.000000,0.000000,31,True,1.493472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43,26,0.020178,48,17,0,0.031233,41.657986,0,0,0.929744,0.029918,0.074119,0.097867,0.137491,-161.078354,86.533691,29.848312,20.791037,False,366,79042.900408,11.173158,7074.356445,13.442710,43,37143.201972,32.648987,1137.652466,13.913844,42,59956.972534,21.079111,2844.378662,12.803296,0,0,0,0,0,1.228449,1.110548,0.471134,0.639414,NaN,NaN,0,NaN,NaN,NaN,283.721464,-41.476288,335.027062,-76.912050,-0.031329,0.291478,3443.771729,3342.938232,3541.565918,3483.971191,3378.533447,3580.282227,10033
3,03373408-6841062,131116000501005,4667335913977929728,4667335913977929728,0.028930,-0.008415,True,1636042515805110273,Gaia EDR3 4667335913977929728,1591815672,2016.0,54.392074,0.019150,-68.685000,0.019368,1.218306,0.019068,63.893230,18.107489,4.351476,0.024009,17.576854,0.022759,0.106125,0.085689,-0.343663,-0.270862,0.075446,-0.256396,-0.253727,0.101832,-0.238310,0.155107,303,0,301,2,21.050278,1175.087524,0.177046,26.554602,31,False,1.531119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,27,0.036738,38,17,0,0.025795,73.736145,0,0,1.978536,0.169714,0.048154,0.045083,0.059608,-6.022393,67.054436,27.120165,6.023081,False,308,87674.674391,18.848673,4651.503906,13.330181,35,45049.926456,40.827145,1103.430786,13.704307,32,61053.057260,33.608616,1816.589478,12.783627,0,0,0,0,0,1.210190,0.920680,0.374125,0.546555,NaN,NaN,0,NaN,NaN,NaN,284.059066,-41.833071,334.836609,-76.477309,-0.031954,1.250260,798.638184,787.818604,810.052979,800.286011,789.345398,811.077881,10033
4,03430488-6843208,131116000501006,4667323681911007232,4667323681911007232,0.245504,-0.003933,True,1636042515805110273,Gaia EDR3 4667323681911007232,750362433,2016.0,55.770496,0.024151,-68.722452,0.026571,2.415489,0.025112,96.187370,9.056929,4.634147,0.030948,7.781557,0.037286,0.012437,0.036670,-0.020751,-0.293523,0.059609,-0.273150,0.008349,-0.017349,-0.190982,0.059561,338,338,338,0,43.823936,5093.051270,0.289947,123.374619,31,True,1.545919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,26,0.052442,46,15,0,0.025943,43.167770,0,0,3.111759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,369,220260.995884,44.442535,4956.085449,12.330023,45,116392.805188,68.208092,1706.436890,12.673727,43,149450.516611,46.213150,3233.939209,11.811652,0,0,0,0,0,1.206947,0.862075,0.343704,0.518371,28.709490,1.654053,15,5500.0,4.5,0.0,283.697372,-41.410086,334.953223,-76.978613,-0.017053,2.432542,411.515839,408.134827,415.689545,411.509003,406.695099,415.063324,10033

In [6]:
# Named two variables for the columns
print(df.columns.tolist())
print(gaia_df.columns.tolist())

['star_id', 'sobject_id', 'dr2_source_id', 'dr3_source_id', 'survey_name', 'field_id', 'flag_repeat', 'wg4_field', 'wg4_pipeline', 'flag_sp', 'teff', 'e_teff', 'irfm_teff', 'irfm_ebv', 'irfm_ebv_ref', 'logg', 'e_logg', 'fe_h', 'e_fe_h', 'flag_fe_h', 'fe_h_atmo', 'vmic', 'vbroad', 'e_vbroad', 'chi2_sp', 'alpha_fe', 'e_alpha_fe', 'nr_alpha_fe', 'flag_alpha_fe', 'flux_A_Fe', 'chi_A_Fe', 'Li_fe', 'e_Li_fe', 'nr_Li_fe', 'flag_Li_fe', 'C_fe', 'e_C_fe', 'nr_C_fe', 'flag_C_fe', 'O_fe', 'e_O_fe', 'nr_O_fe', 'flag_O_fe', 'Na_fe', 'e_Na_fe', 'nr_Na_fe', 'flag_Na_fe', 'Mg_fe', 'e_Mg_fe', 'nr_Mg_fe', 'flag_Mg_fe', 'Al_fe', 'e_Al_fe', 'nr_Al_fe', 'flag_Al_fe', 'Si_fe', 'e_Si_fe', 'nr_Si_fe', 'flag_Si_fe', 'K_fe', 'e_K_fe', 'nr_K_fe', 'flag_K_fe', 'Ca_fe', 'e_Ca_fe', 'nr_Ca_fe', 'flag_Ca_fe', 'Sc_fe', 'e_Sc_fe', 'nr_Sc_fe', 'flag_Sc_fe', 'Sc2_fe', 'e_Sc2_fe', 'nr_Sc2_fe', 'flag_Sc2_fe', 'Ti_fe', 'e_Ti_fe', 'nr_Ti_fe', 'flag_Ti_fe', 'Ti2_fe', 'e_Ti2_fe', 'nr_Ti2_fe', 'flag_Ti2_fe', 'V_fe', 'e_V_fe', 'nr_V_fe', 'flag_V_fe', 'Cr_fe', 'e_Cr_fe', 'nr_Cr_fe', 'flag_Cr_fe', 'Cr2_fe', 'e_Cr2_fe', 'nr_Cr2_fe', 'flag_Cr2_fe', 'Mn_fe', 'e_Mn_fe', 'nr_Mn_fe', 'flag_Mn_fe', 'Co_fe', 'e_Co_fe', 'nr_Co_fe', 'flag_Co_fe', 'Ni_fe', 'e_Ni_fe', 'nr_Ni_fe', 'flag_Ni_fe', 'Cu_fe', 'e_Cu_fe', 'nr_Cu_fe', 'flag_Cu_fe', 'Zn_fe', 'e_Zn_fe', 'nr_Zn_fe', 'flag_Zn_fe', 'Rb_fe', 'e_Rb_fe', 'nr_Rb_fe', 'flag_Rb_fe', 'Sr_fe', 'e_Sr_fe', 'nr_Sr_fe', 'flag_Sr_fe', 'Y_fe', 'e_Y_fe', 'nr_Y_fe', 'flag_Y_fe', 'Zr_fe', 'e_Zr_fe', 'nr_Zr_fe', 'flag_Zr_fe', 'Mo_fe', 'e_Mo_fe', 'nr_Mo_fe', 'flag_Mo_fe', 'Ru_fe', 'e_Ru_fe', 'nr_Ru_fe', 'flag_Ru_fe', 'Ba_fe', 'e_Ba_fe', 'nr_Ba_fe', 'flag_Ba_fe', 'La_fe', 'e_La_fe', 'nr_La_fe', 'flag_La_fe', 'Ce_fe', 'e_Ce_fe', 'nr_Ce_fe', 'flag_Ce_fe', 'Nd_fe', 'e_Nd_fe', 'nr_Nd_fe', 'flag_Nd_fe', 'Sm_fe', 'e_Sm_fe', 'nr_Sm_fe', 'flag_Sm_fe', 'Eu_fe', 'e_Eu_fe', 'nr_Eu_fe', 'flag_Eu_fe', 'ra_dr2', 'dec_dr2', 'parallax_dr2', 'parallax_error_dr2', 'r_est_dr2', 'r_lo_dr2', 'r_hi_dr2', 'r_len_dr2', 'rv_galah', 'e_rv_galah', 'rv_gaia_dr2', 'e_rv_gaia_dr2', 'red_flag', 'ebv', 'snr_c1_iraf', 'snr_c2_iraf', 'snr_c3_iraf', 'snr_c4_iraf', 'flag_guess', 'v_jk', 'j_m', 'j_msigcom', 'h_m', 'h_msigcom', 'ks_m', 'ks_msigcom', 'ph_qual_tmass', 'w2mpro', 'w2mpro_error', 'ph_qual_wise', 'a_ks', 'e_a_ks', 'bc_ks', 'ruwe_dr2']
['star_id', 'sobject_id', 'dr2_source_id', 'dr3_source_id', 'angular_distance', 'magnitude_difference', 'proper_motion_propagation', 'solution_id', 'designation', 'random_index', 'ref_epoch', 'ra', 'ra_error', 'dec', 'dec_error', 'parallax', 'parallax_error', 'parallax_over_error', 'pm', 'pmra', 'pmra_error', 'pmdec', 'pmdec_error', 'ra_dec_corr', 'ra_parallax_corr', 'ra_pmra_corr', 'ra_pmdec_corr', 'dec_parallax_corr', 'dec_pmra_corr', 'dec_pmdec_corr', 'parallax_pmra_corr', 'parallax_pmdec_corr', 'pmra_pmdec_corr', 'astrometric_n_obs_al', 'astrometric_n_obs_ac', 'astrometric_n_good_obs_al', 'astrometric_n_bad_obs_al', 'astrometric_gof_al', 'astrometric_chi2_al', 'astrometric_excess_noise', 'astrometric_excess_noise_sig', 'astrometric_params_solved', 'astrometric_primary_flag', 'nu_eff_used_in_astrometry', 'pseudocolour', 'pseudocolour_error', 'ra_pseudocolour_corr', 'dec_pseudocolour_corr', 'parallax_pseudocolour_corr', 'pmra_pseudocolour_corr', 'pmdec_pseudocolour_corr', 'astrometric_matched_transits', 'visibility_periods_used', 'astrometric_sigma5d_max', 'matched_transits', 'new_matched_transits', 'matched_transits_removed', 'ipd_gof_harmonic_amplitude', 'ipd_gof_harmonic_phase', 'ipd_frac_multi_peak', 'ipd_frac_odd_win', 'ruwe', 'scan_direction_strength_k1', 'scan_direction_strength_k2', 'scan_direction_strength_k3', 'scan_direction_strength_k4', 'scan_direction_mean_k1', 'scan_direction_mean_k2', 'scan_direction_mean_k3', 'scan_direction_mean_k4', 'duplicated_source', 'phot_g_n_obs', 'phot_g_mean_flux', 'phot_g_mean_flux_error', 'phot_g_mean_flux_over_error', 'phot_g_mean_mag', 'phot_bp_n_obs', 'phot_bp_mean_flux', 'phot_bp_mean_flux_error', 'phot_bp_mean_flux_over_error', 'phot_bp_mean_mag', 'phot_rp_n_obs', 'phot_rp_mean_flux', 'phot_rp_mean_flux_error', 'phot_rp_mean_flux_over_error', 'phot_rp_mean_mag', 'phot_bp_n_contaminated_transits', 'phot_bp_n_blended_transits', 'phot_rp_n_contaminated_transits', 'phot_rp_n_blended_transits', 'phot_proc_mode', 'phot_bp_rp_excess_factor', 'bp_rp', 'bp_g', 'g_rp', 'dr2_radial_velocity', 'dr2_radial_velocity_error', 'dr2_rv_nb_transits', 'dr2_rv_template_teff', 'dr2_rv_template_logg', 'dr2_rv_template_fe_h', 'l', 'b', 'ecl_lon', 'ecl_lat', 'zpt_ll2020', 'parallax_corr', 'r_med_geo', 'r_lo_geo', 'r_hi_geo', 'r_med_photogeo', 'r_lo_photogeo', 'r_hi_photogeo', 'flag_edr3dist']

In [81]:
# Merge the two dataframes on the common column "dr3_source_id" and "source_id" 
merged = pd.merge(
    df,
    gaia_df,
    on="dr3_source_id",
    how="inner"
)

In [82]:
# Test run the merged columns
print(merged.columns.tolist())

['star_id_x', 'sobject_id_x', 'dr2_source_id_x', 'dr3_source_id', 'survey_name', 'field_id', 'flag_repeat', 'wg4_field', 'wg4_pipeline', 'flag_sp', 'teff', 'e_teff', 'irfm_teff', 'irfm_ebv', 'irfm_ebv_ref', 'logg', 'e_logg', 'fe_h', 'e_fe_h', 'flag_fe_h', 'fe_h_atmo', 'vmic', 'vbroad', 'e_vbroad', 'chi2_sp', 'alpha_fe', 'e_alpha_fe', 'nr_alpha_fe', 'flag_alpha_fe', 'flux_A_Fe', 'chi_A_Fe', 'Li_fe', 'e_Li_fe', 'nr_Li_fe', 'flag_Li_fe', 'C_fe', 'e_C_fe', 'nr_C_fe', 'flag_C_fe', 'O_fe', 'e_O_fe', 'nr_O_fe', 'flag_O_fe', 'Na_fe', 'e_Na_fe', 'nr_Na_fe', 'flag_Na_fe', 'Mg_fe', 'e_Mg_fe', 'nr_Mg_fe', 'flag_Mg_fe', 'Al_fe', 'e_Al_fe', 'nr_Al_fe', 'flag_Al_fe', 'Si_fe', 'e_Si_fe', 'nr_Si_fe', 'flag_Si_fe', 'K_fe', 'e_K_fe', 'nr_K_fe', 'flag_K_fe', 'Ca_fe', 'e_Ca_fe', 'nr_Ca_fe', 'flag_Ca_fe', 'Sc_fe', 'e_Sc_fe', 'nr_Sc_fe', 'flag_Sc_fe', 'Sc2_fe', 'e_Sc2_fe', 'nr_Sc2_fe', 'flag_Sc2_fe', 'Ti_fe', 'e_Ti_fe', 'nr_Ti_fe', 'flag_Ti_fe', 'Ti2_fe', 'e_Ti2_fe', 'nr_Ti2_fe', 'flag_Ti2_fe', 'V_fe', 'e_V_fe', 'nr_V_fe', 'flag_V_fe', 'Cr_fe', 'e_Cr_fe', 'nr_Cr_fe', 'flag_Cr_fe', 'Cr2_fe', 'e_Cr2_fe', 'nr_Cr2_fe', 'flag_Cr2_fe', 'Mn_fe', 'e_Mn_fe', 'nr_Mn_fe', 'flag_Mn_fe', 'Co_fe', 'e_Co_fe', 'nr_Co_fe', 'flag_Co_fe', 'Ni_fe', 'e_Ni_fe', 'nr_Ni_fe', 'flag_Ni_fe', 'Cu_fe', 'e_Cu_fe', 'nr_Cu_fe', 'flag_Cu_fe', 'Zn_fe', 'e_Zn_fe', 'nr_Zn_fe', 'flag_Zn_fe', 'Rb_fe', 'e_Rb_fe', 'nr_Rb_fe', 'flag_Rb_fe', 'Sr_fe', 'e_Sr_fe', 'nr_Sr_fe', 'flag_Sr_fe', 'Y_fe', 'e_Y_fe', 'nr_Y_fe', 'flag_Y_fe', 'Zr_fe', 'e_Zr_fe', 'nr_Zr_fe', 'flag_Zr_fe', 'Mo_fe', 'e_Mo_fe', 'nr_Mo_fe', 'flag_Mo_fe', 'Ru_fe', 'e_Ru_fe', 'nr_Ru_fe', 'flag_Ru_fe', 'Ba_fe', 'e_Ba_fe', 'nr_Ba_fe', 'flag_Ba_fe', 'La_fe', 'e_La_fe', 'nr_La_fe', 'flag_La_fe', 'Ce_fe', 'e_Ce_fe', 'nr_Ce_fe', 'flag_Ce_fe', 'Nd_fe', 'e_Nd_fe', 'nr_Nd_fe', 'flag_Nd_fe', 'Sm_fe', 'e_Sm_fe', 'nr_Sm_fe', 'flag_Sm_fe', 'Eu_fe', 'e_Eu_fe', 'nr_Eu_fe', 'flag_Eu_fe', 'ra_dr2', 'dec_dr2', 'parallax_dr2', 'parallax_error_dr2', 'r_est_dr2', 'r_lo_dr2', 'r_hi_dr2', 'r_len_dr2', 'rv_galah', 'e_rv_galah', 'rv_gaia_dr2', 'e_rv_gaia_dr2', 'red_flag', 'ebv', 'snr_c1_iraf', 'snr_c2_iraf', 'snr_c3_iraf', 'snr_c4_iraf', 'flag_guess', 'v_jk', 'j_m', 'j_msigcom', 'h_m', 'h_msigcom', 'ks_m', 'ks_msigcom', 'ph_qual_tmass', 'w2mpro', 'w2mpro_error', 'ph_qual_wise', 'a_ks', 'e_a_ks', 'bc_ks', 'ruwe_dr2', 'star_id_y', 'sobject_id_y', 'dr2_source_id_y', 'angular_distance', 'magnitude_difference', 'proper_motion_propagation', 'solution_id', 'designation', 'random_index', 'ref_epoch', 'ra', 'ra_error', 'dec', 'dec_error', 'parallax', 'parallax_error', 'parallax_over_error', 'pm', 'pmra', 'pmra_error', 'pmdec', 'pmdec_error', 'ra_dec_corr', 'ra_parallax_corr', 'ra_pmra_corr', 'ra_pmdec_corr', 'dec_parallax_corr', 'dec_pmra_corr', 'dec_pmdec_corr', 'parallax_pmra_corr', 'parallax_pmdec_corr', 'pmra_pmdec_corr', 'astrometric_n_obs_al', 'astrometric_n_obs_ac', 'astrometric_n_good_obs_al', 'astrometric_n_bad_obs_al', 'astrometric_gof_al', 'astrometric_chi2_al', 'astrometric_excess_noise', 'astrometric_excess_noise_sig', 'astrometric_params_solved', 'astrometric_primary_flag', 'nu_eff_used_in_astrometry', 'pseudocolour', 'pseudocolour_error', 'ra_pseudocolour_corr', 'dec_pseudocolour_corr', 'parallax_pseudocolour_corr', 'pmra_pseudocolour_corr', 'pmdec_pseudocolour_corr', 'astrometric_matched_transits', 'visibility_periods_used', 'astrometric_sigma5d_max', 'matched_transits', 'new_matched_transits', 'matched_transits_removed', 'ipd_gof_harmonic_amplitude', 'ipd_gof_harmonic_phase', 'ipd_frac_multi_peak', 'ipd_frac_odd_win', 'ruwe', 'scan_direction_strength_k1', 'scan_direction_strength_k2', 'scan_direction_strength_k3', 'scan_direction_strength_k4', 'scan_direction_mean_k1', 'scan_direction_mean_k2', 'scan_direction_mean_k3', 'scan_direction_mean_k4', 'duplicated_source', 'phot_g_n_obs', 'phot_g_mean_flux', 'phot_g_mean_flux_error', 'phot_g_mean_flux_over_error', 'phot_g_mean_mag', 'phot_bp_n_obs', 'phot_bp_mean_flux', 'phot_bp_mean_flux_error', 'phot_bp_mean_flux_over_error', 'phot_bp_mean_mag', 'phot_rp_n_obs', 'phot_rp_mean_flux', 'phot_rp_mean_flux_error', 'phot_rp_mean_flux_over_error', 'phot_rp_mean_mag', 'phot_bp_n_contaminated_transits', 'phot_bp_n_blended_transits', 'phot_rp_n_contaminated_transits', 'phot_rp_n_blended_transits', 'phot_proc_mode', 'phot_bp_rp_excess_factor', 'bp_rp', 'bp_g', 'g_rp', 'dr2_radial_velocity', 'dr2_radial_velocity_error', 'dr2_rv_nb_transits', 'dr2_rv_template_teff', 'dr2_rv_template_logg', 'dr2_rv_template_fe_h', 'l', 'b', 'ecl_lon', 'ecl_lat', 'zpt_ll2020', 'parallax_corr', 'r_med_geo', 'r_lo_geo', 'r_hi_geo', 'r_med_photogeo', 'r_lo_photogeo', 'r_hi_photogeo', 'flag_edr3dist']

In [ ]:
# =========================
# 2. Data cleaning
# =========================
# Create a neww table with the core columns for the analysis
analysis_df = merged[[
    "dr3_source_id",
    "ra",
    "dec",
    "l",
    "b",
    "parallax",
    "pmra",
    "pmdec",
    "rv_galah",
    "teff",
    "logg",
    "fe_h"
]].copy()

In [84]:
# Eliminate rows with missing values in the core columns
analysis_df=analysis_df.dropna(subset=["ra", "dec", "pmra", "pmdec", "fe_h", "rv_galah", "parallax", "l", "b"])

# Quick check of the cleaned data
analysis_df.head()
print("Number of stars after cleaning:", len(analysis_df))

Number of stars after cleaning: 649172

In [85]:
# Double check if there are any repeated Gaia source IDs
analysis_df = analysis_df.drop_duplicates(subset="dr3_source_id")
print("Number of stars after removing duplicates:", len(analysis_df))

Number of stars after removing duplicates: 565866

In [1]:
# =========================
# 3. Sky distribution
# =========================
# Data looks good so far, proceeding to the next steps of the analysis and plotting.
from matplotlib.pylab import sample
plt.figure(figsize=(10,6))
plt.scatter(
    analysis_df["l"],
    analysis_df["b"],
    s=0.3,
    alpha=0.3
)
plt.xlabel("Galactic Longitude (l)[degrees]")
plt.ylabel("Galactic Latitude (b)[degrees]")
plt.title("Spatial Distribution of Stars in GALAH–Gaia Coordinates")
plt.show()

NameError: name 'plt' is not defined